export const SCORING = {
  MODEL_TEMPERATURE: 0,
  MAX_TOKENS: 900,
  BATCH_MAX_TOKENS: 1800,
  CANDIDATE_CONTENT_MAX_CHARS: 6000,
  WEIGHTS: {
    ENTERPRISE_RELEVANCE: 0.2,
    WORKFLOW_REDESIGN_DEPTH: 0.2,
    REAL_USE_CASE_SPECIFICITY: 0.15,
    DEPLOYMENT_FDE_RELEVANCE: 0.15,
    BUSINESS_OUTCOME_CLARITY: 0.1,
    TECHNICAL_IMPLEMENTATION_USEFULNESS: 0.1,
    RECENCY: 0.05,
    NON_GENERIC_INSIGHT: 0.05,
  },
  SYSTEM_PROMPT: [
    "You score reading candidates for an enterprise AI deployment scout.",
    "Return exactly one valid JSON object and no prose outside JSON.",
    "Do not use Markdown, bullets, code fences, comments, or explanations outside the JSON object.",
    "Score each numeric field as an integer from 1 to 5.",
    "Prefer concrete enterprise deployment evidence: workflows, operating model changes, ROI, governance, field deployment, implementation details, customer rollout lessons, or FDE-style delivery relevance.",
    "Hard reject generic AI news, tool launch hype, prompting tips, top 10 AI tools posts, shallow opinion pieces, pure research without enterprise deployment relevance, and content with no workflow, operating model, ROI, or implementation angle.",
    "If rejected is true, set every numeric score to 1 and include a concise rejectionReason.",
  ].join("\n"),
  USER_PROMPT_LABELS: {
    INTERESTS: "Interests",
    AVOID: "Avoid terms",
    PREFERRED_DIFFICULTY: "Preferred difficulty",
    DAILY_MIX: "Daily source mix",
    CANDIDATE: "Candidate",
    RESPONSE_SHAPE: "Return JSON with exactly these fields",
  },
  REPAIR_PROMPT:
    "Your previous response was not valid JSON. Return only one valid JSON object matching the requested fields.",
  RESPONSE_FIELDS: {
    ENTERPRISE_RELEVANCE: "enterpriseRelevance",
    WORKFLOW_REDESIGN_DEPTH: "workflowRedesignDepth",
    REAL_USE_CASE_SPECIFICITY: "realUseCaseSpecificity",
    DEPLOYMENT_FDE_RELEVANCE: "deploymentFdeRelevance",
    BUSINESS_OUTCOME_CLARITY: "businessOutcomeClarity",
    TECHNICAL_IMPLEMENTATION_USEFULNESS: "technicalImplementationUsefulness",
    RECENCY: "recency",
    NON_GENERIC_INSIGHT: "nonGenericInsight",
    REJECTED: "rejected",
    REJECTION_REASON: "rejectionReason",
    REASON: "reason",
  },
  ERRORS: {
    INVALID_SCORE: "Model returned an invalid item score.",
  },
} as const;
