export const AGENT = {
  DEFAULT_MAX_STEPS: 8,
  MODEL_MAX_TOKENS: 1_000,
  MAX_RESPONSE_CHARS: 20_000,
  TOOL_RESULT_TYPE: "tool_result",
  ROLES: {
    SYSTEM: "system",
    USER: "user",
    ASSISTANT: "assistant",
  },
  RESPONSE_TYPES: {
    FINAL: "final",
    TOOL_CALL: "tool_call",
    CLARIFY: "clarify",
  },
  ERRORS: {
    INVALID_RESPONSE_PREFIX: "Agent returned an invalid response:",
    MAX_STEPS_PREFIX: "Agent stopped after reaching the maximum step limit of",
    CLARIFICATION_PREFIX: "Clarification needed:",
  },
  LOG_EVENTS: {
    RUN_START: "agent.run.start",
    HARNESS_TO_MODEL: "handoff.harness_to_model",
    MODEL_TO_HARNESS: "handoff.model_to_harness",
    RESPONSE_PARSE_FAILED: "agent.response.parse_failed",
    RESPONSE_PARSED: "agent.response.parsed",
    RUN_FINAL: "agent.run.final",
    RUN_CLARIFY: "agent.run.clarify",
    HARNESS_TO_TOOL: "handoff.harness_to_tool",
    TOOL_TO_HARNESS: "handoff.tool_to_harness",
    APPEND_TOOL_RESULT: "agent.messages.append_tool_result",
    MAX_STEPS: "agent.run.max_steps",
  },
  LOG_MESSAGES: {
    RUN_START: "agent run started",
    HARNESS_TO_MODEL: "sending messages to model",
    MODEL_TO_HARNESS: "received model response",
    RESPONSE_PARSE_FAILED: "model response failed protocol parsing",
    RESPONSE_PARSED: "parsed model response",
    RUN_FINAL: "agent run completed with final answer",
    RUN_CLARIFY: "agent run completed with clarification request",
    HARNESS_TO_TOOL: "dispatching tool call",
    TOOL_TO_HARNESS: "received tool result",
    APPEND_TOOL_RESULT: "appended tool result message",
    MAX_STEPS: "agent run reached max step limit",
  },
} as const;
