// Purpose: Collects shared url text constants.
// Scope: Avoids scattering repeated literals across runtime modules.

export const URL_TEXT = {
  DEFAULT_MAX_CHARS: 12_000,
  MAX_CHARS_LIMIT: 30_000,
  EMPTY_TITLE: "",
  PAYWALL_PATTERNS: [
    "subscribe to continue",
    "subscription required",
    "sign in to continue",
    "log in to continue",
    "already a subscriber",
    "metered access",
    "paywall",
  ],
  TAGS_TO_DROP: [
    "script",
    "style",
    "head",
    "noscript",
    "svg",
    "iframe",
    "nav",
    "footer",
    "header",
    "aside",
    "form",
  ],
  BLOCK_TAGS: [
    "article",
    "main",
    "section",
    "div",
    "p",
    "br",
    "li",
    "ul",
    "ol",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "blockquote",
    "pre",
    "table",
    "tr",
  ],
  ERRORS: {
    HTTP_FAILED_PREFIX: "URL text request failed with HTTP",
    INVALID_MAX_CHARS: "max_chars must be an integer between 1 and 30000.",
    TOO_MANY_REDIRECTS: "URL text request exceeded the redirect limit.",
  },
} as const;
