export const USE_CASES = {
  DIRECTORY: "config",
  FILE_NAME: "production-use-case-scout.json",
  REPORT_DIRECTORY: "use-case-reports",
  FILE_EXTENSION: ".md",
  DATE_LENGTH: 10,
  DATE_PATTERN: /^\d{4}-\d{2}-\d{2}$/,
  TITLE: "Production Enterprise AI Use Cases",
  DEFAULT_MAX_SEARCH_RESULTS_PER_QUERY: 5,
  DEFAULT_MAX_CANDIDATES_FOR_EXTRACTION: 30,
  DEFAULT_MAX_RESULTS: 10,
  MAX_ERROR_MESSAGE_LENGTH: 500,
  MODEL_TEMPERATURE: 0,
  MAX_TOKENS: 900,
  MAX_ATTEMPTS: 2,
  SYSTEM_PROMPT: [
    "You extract real, in-production enterprise AI use cases from source material.",
    "Return exactly one valid JSON object and no prose outside JSON.",
    "Accept only if the source gives a named company, a real enterprise workflow, live deployment or rollout evidence, a concrete business metric or operational outcome, a reference link, and a publish date.",
    "Reject generic articles, trend pieces, vendor launches without named customers, pilots without production evidence, and consulting frameworks without concrete company examples.",
  ].join("\n"),
  USER_PROMPT_LABELS: {
    SEARCH_RESULT: "Search result",
    FETCHED_CONTENT: "Fetched content",
    RESPONSE_SHAPE: "Return JSON with exactly this shape",
  },
  RESPONSE_FIELDS: {
    ACCEPTED: "accepted",
    REJECTION_REASON: "rejectionReason",
    COMPANY: "company",
    WORKFLOW: "workflow",
    WHAT_AI_DOES: "whatAiDoes",
    PRODUCTION_EVIDENCE: "productionEvidence",
    BUSINESS_METRIC: "businessMetric",
    SOURCE_LINK: "sourceLink",
    PUBLISH_DATE: "publishDate",
    WHY_THIS_MATTERS: "whyThisMattersForEnterpriseAiWorkflowRedesign",
  },
  REPAIR_PROMPT:
    "Your previous response was not valid JSON. Return only one valid JSON object matching the requested fields.",
  ERRORS: {
    INVALID_JSON: "Production use case scout config is not valid JSON.",
    INVALID_CONFIG: "Production use case scout config is invalid.",
    INVALID_EXTRACTION: "Model returned an invalid production use case extraction.",
    INVALID_DATE: "Use case report date must be formatted as YYYY-MM-DD.",
    INVALID_MAX_RESULTS: "max results must be a positive integer.",
  },
} as const;
